### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by zwt1101** [HUANGLIZI/ScribFormer#1]
Hello, during testing, I encountered a sit k:: Error: The file "../data/ACDC_training/patient005_frame01. ni. gz" does not exist. Why is this error

**Comment by HUANGLIZI** [comment]
please prepare the data before testing.

**Comment by irui3** [comment]
> 请在测试前准备好数据。

Hello, I have this dataset/Data/ADCtraining \ ADC \ ADCtraining_volumes, and during testing, I also output patient005'frame01.h5, but there is a site:: Error: The file "../Data/ADCtraining/patient005'frame01. ni. gz" does not exist

**Comment by zwt1101** [comment]
> 请在测试前准备好数据。

Hello, I have this dataset/Data/ADCtraining \ ADC \ ADCtraining_volumes, and during testing, I also output patient005'frame01.h5, but there is a site:: Error: The file "../Data/ADCtraining/patient005'frame01. ni. gz" does not exist

**Comment by zwt1101** [comment]
> 请在测试前准备好数据。

Thank you for your help. This is because I didn't prepare to test the dataset
