### ISSUE TITLE
On the visualization of class activation diagrams

### ISSUE THREAD

**Issue by QuintinDong** [HUANGLIZI/ScribFormer#4]
Thanks to the authors for their work! May I ask what I should do if I want to save and visualize the class activation diagram as in your paper? I would be grateful for your answer.

**Comment by HUANGLIZI** [comment]
Please feel free to use the repo https://github.com/jacobgil/pytorch-grad-cam

**Comment by QuintinDong** [comment]
> Please feel free to use the repo https://github.com/jacobgil/pytorch-grad-cam
Thank you for your reply. I'm going to try it now！

**Comment by QuintinDong** [comment]
> Please feel free to use the repo https://github.com/jacobgil/pytorch-grad-cam

I tried it and still have some doubts. In cam you need to set the parameter of the corresponding layer, for example target_layers = [model.layer4[-1]]. May I ask how you set this up? I will be grateful if you can answer!

**Comment by HUANGLIZI** [comment]
You can check the setting in the paper. And we visualize both the encoder and decoder layers.

**Comment by QuintinDong** [comment]
> You can check the setting in the paper. And we visualize both the encoder and decoder layers.

Thank you for your reply. However, I have made many attempts and still have not been able to visualize the results in your paper. If it is convenient, could you send a copy of the code for the class activation graph visualization to my email? I will be grateful if it is possible! 我的邮箱是qcd2515427305@163.com
