### ISSUE TITLE
The direction of FCU in the paper.

### ISSUE THREAD

**Issue by Zxl19990529** [HUANGLIZI/ScribFormer#6]
It seems that, the trans/CNN direction of FCU between Figure 2 and Figure 3 is opposite. I mean in the paper. https://arxiv.org/pdf/2402.02029

**Comment by HUANGLIZI** [comment]
Thanks for your message. The FCU interaction in Figure 2 is only a demo diagram, representing the existence of bidirectional feature transfer, rather than the order of upsampling and downsampling. If you want to check the order of them, you should just focus on the Fig 3.
