### ISSUE TITLE
测试文件中的ACDC_training文件夹是哪里来的

### ISSUE THREAD

**Issue by naadurian** [HUANGLIZI/ScribFormer#7]
作者您好，我对您的这个项目很感兴趣，近日在复现它，今天我运行test.py文件的时候发现报错总是找不到../data/ACDC_training/patient005_frame01.nii.gz文件，我看了test文件之后发现只有91行中有ACDC_training文件，但是我不知道这个文件是哪里生成的，想知道这个确实是ACDC_training而不是ACDC_training_volumes或者ACDC_training_slices吗？

**Comment by HUANGLIZI** [comment]
Please refer to the repo: https://github.com/BWGZK/CycleMIx or https://github.com/HUANGLIZI/ScribbleVC

**Comment by naadurian** [comment]
> 请参考 repo：[https](https://github.com/BWGZK/CycleMIx) ://github.com/BWGZK/CycleMIx或https://github.com/HUANGLIZI/ScribbleVC

Ok，thank you very much!
