### ISSUE TITLE
dataset-MSCMR 

### ISSUE THREAD

**Issue by naadurian** [HUANGLIZI/ScribFormer#8]
Hello author, would like to ask the data set downloaded through this link “The scribble-annotated MSCMR dataset used for training could be directly downloaded from [MSCMR_dataset].” , is it mask or scribble or mix ?

**Comment by HUANGLIZI** [comment]
It is scribble annotation. The download link is here:
https://github.com/BWGZK/CycleMix/tree/main/MSCMR_scribbles

**Comment by naadurian** [comment]
Ok, thank you very much for sharing
&nbsp;


嘿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zihan ***@***.***&gt;; 
发送时间: 2024年12月10日(星期二) 凌晨3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HUANGLIZI/ScribFormer] dataset-MSCMR  (Issue #8)














 
It is scribble annotation. The download link is here:
 https://github.com/BWGZK/CycleMix/tree/main/MSCMR_scribbles
